### ISSUE TITLE
Deoplete slows to a crawl when using deoplete-clangx with neoinclude and a lot of includes

### ISSUE THREAD

**Issue by nonnymoose** [Shougo/deoplete-clangx#10]
Here's an example file: 
[template.cpp.txt](https://github.com/Shougo/deoplete-clangx/files/4568827/template.cpp.txt)

When editing this file, I experience multiple-second delays after switching modes. It makes the editing experience pretty unusable. Disabling deoplete-clangx or neoinclude solves the problem.

Is this a bug, or an issue that can be solved with parallelization, or are there simply too many symbols provided by clang when there are that many includes?

**Comment by Shougo** [comment]
Both neoinclude with deoplete and deoplete-clangx(clang) searches candidates from included files.  The search will be twice!
So you should disable deoplete-clangx or neoinclude.

>  are there simply too many symbols provided by clang when there are that many includes?

Yes.
