### ISSUE TITLE
What to include in init file to start using

### ISSUE THREAD

**Issue by MaxisJaisi** [Shougo/deoplete-clangx#13]
I'm on my Mac laptop, and have clang and all the necessary frameworks installed. In particular, libclang.dylib is located in 

/Library/Developer/CommandLineTools/usr/lib/

What should I include in my nvim init file to begin using the autocomplete feature for C/C++ files? Many thanks.

**Comment by Shougo** [comment]
Sorry.  The plugin is already deprecated.  You should use clang lsp instead.
