### ISSUE TITLE
global options for clangx source

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/deoplete-clangx#3]
@Shougo

Hi, I want to included this plugin into SpaceVim, but now I can not set the clangexectable before deoplete is loaded. I hope this plugins support options like:

```
g:deoplete#sources#clangx#executable

```
as I know, this plugin support `.clang` file, which also used in SpaceVim's c layer, so maybe we do not need:

```
g:deoplete#sources#clangx#std
g:deoplete#sources#clangx#flags
```

**Comment by Shougo** [comment]
Please read README.

**Comment by wsdjeg** [comment]
before deoplete is loaded, we can not use this function thought. I need to set it when vim startup, at that time deoplete is not loaded.

**Comment by Shougo** [comment]
You need to load deoplete.nvim before deoplete-clangx loading.
dein.vim supports the feature.

> I need to set it when vim startup, at that time deoplete is not loaded.

It seems SpaceVim implementation problem.

**Comment by wsdjeg** [comment]
OK, I got it. thank you.
