### ISSUE TITLE
change work dir, clangx can't work.

### ISSUE THREAD

**Issue by fcying** [Shougo/deoplete-clangx#5]
The include path is not set relative to the `.clang_complete` file, is relative to work dir.
```
~/test/test_clang $ tree -a
├── a
│   ├── inc
│   │   └── t.h
│   └── src
│       └── main.c
└── .clang_complete

.clang_complte
-Ia/inc/
```
workdir is root: vim a/src/main.c, work fine
workdir is a: vim src/main.c, can't work

**Comment by Shougo** [comment]
Sorry.  I don't want to support it.
It seems very complex feature.

You can send the PR for it.

Hint:
https://github.com/Shougo/deoplete-clangx/blob/master/rplugin/python3/deoplete/source/clangx.py#L108

**Comment by Shougo** [comment]
You can use `os.path.relpath` for it.

**Comment by fcying** [comment]
tks, I'll try to do this.
