### ISSUE TITLE
Configure include directory for clangx

### ISSUE THREAD

**Issue by lriuui0x0** [Shougo/deoplete-clangx#9]
I'm trying to use clangx with custom input directory without no success. There's no suggestion on types from the library.

I have installed 'Shougo/neoinclude.vim', and I configured clang options as

```
call deoplete#custom#var('clangx', 'default_c_options', ['-I/usr/local/include/lib'])
call deoplete#custom#var('clangx', 'default_cpp_options', ['-I/usr/local/include/lib'])
```

Am I doing something wrong?

**Comment by lriuui0x0** [comment]
There's also another problem. Clangx doesn't suggest template struct fields. I have the following code:

```
template <typename T>
struct Array
{
    T *data;
    int capacity;
    int length;
};

template <typename T>
Array<T> create_array(int capacity)
{
    Array<T> array;
    array.capacity = capacity;
    array.length = 0;
    array.data = (T *)malloc(sizeof(T) * array.capacity);
    return array;
}
```

I have the following code:

```
Array<char> msg_buffer = create_array<char>(4096);
msg_buffer.*
```

And I trigger completion at * position. Nothing happens.

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete-clangx/issues/9#issuecomment-599132538

I have tested it, and it works for me.
So it is not the issue both clang and deoplete-clangx.

**Comment by Shougo** [comment]
The test code is here.

```cpp
#include <string>
#include <vector>

template <typename T>
struct Array
{
    T *data;
    int capacity;
    int length;
};

template <typename T>
Array<T> create_array(int capacity)
{
    Array<T> array;
    array.capacity = capacity;
    array.length = 0;
    array.data = (T *)malloc(sizeof(T) * array.capacity);
    return array;
}

int main(int argc, char **argv) {
  Array<char> msg_buffer = create_array<char>(4096);
  msg_buffer.*
  std::vector<std::string> v;

  return 0;
}
```

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete-clangx/issues/9#issue-581360583

This is bug.  Fixed.

**Comment by lriuui0x0** [comment]
@Shougo Thanks for the fix. I can confirm the suggestion is working now. Weirdly the template suggestion does seem to work now :)

One problem I found is that if you try to complete a struct field, you will have to trigger `g:deoplete#complete()` (mapped to <C-n>) at least twice for the popup to show (sometimes three times but the behaviour is not consistent), whereas if you try to complete a variable, you only need to trigger once.

**Comment by Shougo** [comment]
Unfortunately, it is feature.
You need to know what is `deoplete#complete()`.
It displays for finished completion.
deoplete-clangx is slower than other sources.

So it may not be displayed when you triggered it.

If you need to wait the completion, please use `deoplete#manual_complete()` instead.
`deoplete#complete()` is not perfect solution.

You should know why `deoplete#complete()` exists.
https://github.com/Shougo/deoplete.nvim/issues/1065
